### ISSUE TITLE
Output variables don't reach Github action

### ISSUE THREAD

**Issue by ynsehoornenborg** [philips-software/run-windows-docker-container-action#7]
Hi, 
Thanks for creating this Action, very helpful and nicely build.

I was planning on using this action to build + test in a windows docker container from a Github Action. To report the outcome of this process, I would like output 1 (or more) variables from the Docker container back to the Github Action.

I tried the following action definition:
```yaml
name: 'Buid on Philips hosted Windows Docker container'

on: [push]

jobs:
  build:

    runs-on: [self-hosted, windows, x64, philips-code-hub, servercore-2022]

    steps:
      - uses: actions/checkout@v3
      - name: Test_Run
        id: docker
        uses: philips-software/run-windows-docker-container-action@v1.0.2
        with:
            image: dl-innersource-docker.artifactory-ehv.ta.philips.com/windows/servercore/buildtools/2022:latest
            entrypoint: powershell.exe
            run: >-
                ./.github/BuildInDocker/entrypoint.ps1;
      - name: Get the output
        run: echo "The number of failed test cases was ${{ steps.docker.outputs.numfailed }}"
```

With the code of the entrypoint.ps1 script that is running _inside_ Docker based loosly on your `set_output_variable.ps1`, like this:
```ps1 
# set github output with name and value
function toGitHub  {
    param(
        $output_name,
        $output_value
    )
    "$output_name=$output_value" >> $env:GITHUB_OUTPUT;
}

# Report zero failed test cases
Write-Host "The number of failed test cases is: 0"
toGitHub -output_name "numfailed" -output_value "0"
```

The dots don't seem to connect somehow. Am I missing something ?
